name: trivy
description: Run Trivy to scan Terraform code for security issues

inputs:
  github_token:
    description: 'GitHub token for Trivy'
    required: true
  severity:
    description: 'Severity levels to scan for (e.g., HIGH,CRITICAL)'
    default: 'HIGH,CRITICAL'
    required: false
  tf_plan_file:
    description: 'Path to Terraform plan JSON file (optional)'
    default: ''
    required: false

runs:
  using: "composite"
  steps:

    - name: Check out code
      uses: actions/checkout@v4
#sji todo - this is duplicated really so refactor build action to split 
    - name: Get Terraform Version
      uses: ./.github/actions/terraform/version

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
    
    - name: Terraform Init
      run: terraform init -backend-config=backend.hcl -upgrade 
      shell: bash

    - name: Terraform Plan
      shell: bash
      run: |
        terraform plan -out=tf.plan
        terraform show -json tf.plan > tfplan.json
        
    - name: Install Trivy
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.58.1

    - name: Select Trivy config file
      shell: bash
      id: select-config
      run: |
        if [[ "${GITHUB_EVENT_NAME}" == "schedule" && "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "config_file=.trivy-strict.yml" >> $GITHUB_OUTPUT
        else
          echo "config_file=.trivy-relaxed.yml" >> $GITHUB_OUTPUT
        fi

    - name: Run Trivy on Terraform configuration
      shell: bash
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        trivy config --severity ${{ inputs.severity }} --config "${{ github.action_path }}/${{ steps.select-config.outputs.config_file }}" .

    - name: Run Trivy on Terraform plan (if provided)
      shell: bash
      continue-on-error: true
      if: inputs.tf_plan_file != ''
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        trivy config 
          --severity ${{ inputs.severity }} 
          --format table \
          --output trivy-results.sarif \
          --config "${{ github.action_path }}/${{ steps.select-config.outputs.config_file }}" ${{ inputs.tf_plan_file }}

    - name: Upload Trivy SARIF to GitHub
      if: github.event_name == 'schedule' && github.ref == 'refs/heads/main'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif
        category: trivy
    
    # Upload JSON artifact on all other runs
    - name: Upload Trivy JSON Artifact
      if: github.event_name != 'schedule' || github.ref != 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: trivy-json-report
        path: trivy-results.json