name: 'Terraform Version'
description: 'Read the Terraform version from .terraform-version file'

runs:
  using: "composite"
  steps:

    - name: Read Terraform Version
      shell: bash
      id: tf-version
      run: |
        if [ ! -f .terraform-version ]; then
          echo "Error: .terraform-version file not found."
          exit 1
        fi
        version=$(cat .terraform-version)
        echo "Terraform version: $version"
        echo "version=$version" >> $GITHUB_OUTPUT