name: tfsec
description: Run tfsec to check Terraform code for security issues

runs:
  using: "composite"
  steps:

  - name: Run tfsec
    uses: aquasecurity/tfsec-action@v1.0.0
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
