name: Terraform Deployment
# on:
#   workflow_run:
#       workflows: ["Security Scan"]
#       types:
#         - completed
on:
  workflow_dispatch: #change based on env todo sji

permissions:
  contents: write

jobs:
# iif: == 'success' sji! }}
  terraform-deploy:
    name: Terraform Validate
    runs-on: ubuntu-latest
    
    # Specify environment for prod branch - sji todo
    environment: ${{ github.ref_name == 'prod' && 'prod' || '' }}

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.TF_SA }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Authenticate to GCP
      # sji - we should probs use workload identity federation here really
      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TF_SA }}' 
          export_environment_variables: true
                    
      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get Terraform Version
        uses: ./.github/actions/terraform/version

      - name: Terraform Quality Check
        uses: ./.github/actions/terraform/quality
        with:
          terraform_version: ${{ steps.tf-version.outputs.version }}

      - name: Terraform Build
        uses: ./.github/actions/terraform/build
        with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.TF_SA }}           
          
      - name: Terraform Apply
        uses: ./.github/actions/terraform/apply
        with:
          terraform_version: ${{ steps.tf-version.outputs.version }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account: ${{ secrets.TF_SA }}
            
  render-terraform-docs:      
    name: Terraform Docs
    needs: terraform-deploy
    runs-on: ubuntu-latest
    # Run only on pull request merges to main
    #if github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.base_ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      
      # Authenticate to GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TF_SA }}'  # Key from script

      - name: Terraform Docs
        uses: ./.github/actions/terraform/docs

