name: Disable GKE Deletion Protection

on:
  workflow_dispatch:
    inputs:
      target_cluster:
        description: "Which cluster to modify? ('prod' or 'stg' or 'both')"
        required: true
        default: "stg"
        type: choice
        options:
          - prod
          - stg
          - both

jobs:
  disable-protection:
    runs-on: ubuntu-latest
    env:
      PROD_CLUSTER_NAME: k8s-coral-prd
      PROD_CLUSTER_LOCATION: europe-west2-a
      STG_CLUSTER_NAME: k8s-coral-stg
      STG_CLUSTER_LOCATION: europe-west2-a
      TARGET_CLUSTER: ${{ github.event.inputs.target_cluster }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TF_SA }}' 
          export_environment_variables: true

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Disable Deletion Protection
        run: |
          disable_protection() {
            local CLUSTER_NAME=$1
            local CLUSTER_LOCATION=$2
            echo "Disabling deletion protection for cluster: $CLUSTER_NAME in $CLUSTER_LOCATION"
            gcloud container clusters update "$CLUSTER_NAME" \
              --zone "$CLUSTER_LOCATION" \
              --no-deletion-protection
          }

          case "$TARGET_CLUSTER" in
            prod)
              disable_protection "$PROD_CLUSTER_NAME" "$PROD_CLUSTER_LOCATION"
              ;;
            stg)
              disable_protection "$STG_CLUSTER_NAME" "$STG_CLUSTER_LOCATION"
              ;;
            both)
              disable_protection "$PROD_CLUSTER_NAME" "$PROD_CLUSTER_LOCATION"
              disable_protec_
