name: Disable GKE Deletion Protection

on:
  workflow_dispatch:
    inputs:
      target_cluster:
        description: "Which cluster to modify? ('prod', 'stg', or 'both')"
        required: true
        default: "stg"
        type: choice
        options:
          - prod
          - stg
          - both

jobs:
  disable-protection:
    runs-on: ubuntu-latest
    env:
      PROD_CLUSTER_NAME: k8s-coral-prd
      PROD_CLUSTER_ZONE: europe-west2
      STG_CLUSTER_NAME: k8s-coral-stg
      STG_CLUSTER_ZONE: europe-west2
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TF_SA }}'
          export_environment_variables: true

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Disable Deletion Protection
        run: |
          set -x  # Enable debug logging
          disable_protection() {
            local CLUSTER_NAME=$1
            local CLUSTER_ZONE=$2
            echo "Disabling deletion protection for cluster: $CLUSTER_NAME in zone $CLUSTER_ZONE"
            gcloud container clusters update "$CLUSTER_NAME" \
              --zone "$CLUSTER_ZONE" \
              --no-deletion-protection
          }

          case "${{ github.event.inputs.target_cluster }}" in
            prod)
              disable_protection "$PROD_CLUSTER_NAME" "$PROD_CLUSTER_ZONE"
              ;;
            stg)
              disable_protection "$STG_CLUSTER_NAME" "$STG_CLUSTER_ZONE"
              ;;
            both)
              disable_protection "$PROD_CLUSTER_NAME" "$PROD_CLUSTER_ZONE"
              disable_protection "$STG_CLUSTER_NAME" "$STG_CLUSTER_ZONE"
              ;;
            *)
              echo "Invalid input: ${{ github.event.inputs.target_cluster }}"
              exit 1
              ;;
          esac