name: Disable APIs

# on: sji!
#     workflow_run:
#       workflows: ["Security Scan"] sonar?!
#       types:
#         - completed
on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
# iif: == 'success' sji! }}
  disable-apis:
    name: Disable APIs
    # This job disables the APIs that were enabled during the setup process
    runs-on: ubuntu-latest
    
    # Specify environment for prod branch
    environment: ${{ github.ref_name == 'prod' && 'prod' || '' }}

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.TF_BOOTSTRAP_SA }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.TF_BOOTSTRAP_SA }}'  # Key from script
         
      - name: Disable IAM API
        run: |
          gcloud services disable iam.googleapis.com
          gcloud services disable cloudresourcemanager.googleapis.com
          gcloud services disable artifactregistry.googleapis.com
          gcloud services disable compute.googleapis.com
          gcloud services disable kubernetesengine.googleapis.com
          gcloud services disable keymanagement.googleapis.com